# Generated by Django 5.1.1 on 2024-09-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.CharField(
                blank=True, default="", help_text="alias name", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="termname",
            field=models.CharField(
                blank=True, default="", help_text="real term name", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="regex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regular expression to find text to replace",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text to replace in term description",
                max_length=4096,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="comment on proposal",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when proposal was created was published.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="mail_list_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="title of mailing list thread",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="mail_list_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of Mailing list thread",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposed_date",
            field=models.DateField(
                blank=True, help_text="Date when proposal was first made.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposer",
            field=models.CharField(
                blank=True, default="", help_text="name of proposer", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "new"),
                    ("under discussion", "under discussion"),
                    ("rejected", "rejected"),
                    ("complete", "complete"),
                    ("accepted", "accepted"),
                ],
                default="New",
                help_text="Status of request",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="vocab_list",
            field=models.ForeignKey(
                blank=True,
                help_text="If the proposal is accepted the term will be added to a version of this list.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.vocablist",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="vocab_list_version",
            field=models.ForeignKey(
                blank=True,
                help_text="After it was accepted the term was added to this version of the list.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.vocablistversion",
            ),
        ),
        migrations.AlterField(
            model_name="proposedterms",
            name="change_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date the term was last changed."
            ),
        ),
        migrations.AlterField(
            model_name="proposedterms",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proposedterms",
            name="proposal",
            field=models.ForeignKey(
                help_text="Link to Request that generated the term",
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.proposal",
            ),
        ),
        migrations.AlterField(
            model_name="proposedterms",
            name="term",
            field=models.ForeignKey(
                help_text="Link to the term",
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.term",
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="amip",
            field=models.CharField(
                blank=True,
                default="",
                help_text="amip name/number for term",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="description",
            field=models.CharField(
                blank=True, default="", help_text="description of term", max_length=4096
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="externalid",
            field=models.CharField(
                blank=True, default="", help_text="machine readable id", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="grib",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Grib name/number for term",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="name",
            field=models.CharField(
                blank=True, default="", help_text="term text", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="unit",
            field=models.CharField(
                blank=True, default="", help_text="unit", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="unit_ref",
            field=models.CharField(
                blank=True, default="", help_text="reference for unit", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="vocablist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vocablist",
            name="name",
            field=models.CharField(
                blank=True, default="", help_text="title of vocab", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="vocablistversion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vocablistversion",
            name="published_date",
            field=models.DateField(
                auto_now_add=True, help_text="Date when list was published."
            ),
        ),
        migrations.AlterField(
            model_name="vocablistversion",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Blank", "Blank"),
                    ("copied", "copied"),
                    ("Changed", "Changed"),
                    ("Complete", "Complete"),
                ],
                default="Blank",
                help_text="Status of list",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="vocablistversion",
            name="version",
            field=models.IntegerField(help_text="version number of vocab list"),
        ),
        migrations.AlterField(
            model_name="vocablistversion",
            name="vocab_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Vocab list for which this is a version",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.vocablist",
            ),
        ),
    ]
